--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Own
-- Project :      Model1.DM1
-- Author :       Ottoniel
--
-- Date Created : Tuesday, February 23, 2021 18:58:24
-- Target DBMS : MySQL 5.x
--

use db_app;

-- 
-- TABLE: AGENTE 
--

CREATE TABLE AGENTE(
    AGENTEID           DECIMAL(10, 0)    NOT NULL,
    NOMBRES            VARCHAR(100)      NOT NULL,
    APELLIDOS          VARCHAR(100)      NOT NULL,
    CONCESIONARIOID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (AGENTEID)
)ENGINE=MYISAM
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTEID     DECIMAL(10, 0)    NOT NULL,
    NOMBRES       VARCHAR(200)      NOT NULL,
    APELLIDOS     VARCHAR(200)      NOT NULL,
    TELEFONO      VARCHAR(8)        NOT NULL,
    DIRECCION     VARCHAR(300)      NOT NULL,
    NACIMIENTO    DATE              NOT NULL,
    CREADO        DATE              NOT NULL,
    PRIMARY KEY (CLIENTEID)
)ENGINE=MYISAM
;



-- 
-- TABLE: CONCESIONARIO 
--

CREATE TABLE CONCESIONARIO(
    CONCESIONARIOID    DECIMAL(10, 0)    NOT NULL,
    NOMBRE             VARCHAR(200)      NOT NULL,
    DIRECCION          VARCHAR(300)      NOT NULL,
    CREADO             DATE              NOT NULL,
    PRIMARY KEY (CONCESIONARIOID)
)ENGINE=MYISAM
;



-- 
-- TABLE: COTIZACION 
--

CREATE TABLE COTIZACION(
    COTIZACIONID    DECIMAL(10, 0)    NOT NULL,
    AGENTEID        DECIMAL(10, 0)    NOT NULL,
    CLIENTEID       DECIMAL(10, 0)    NOT NULL,
    VEHICULOID      DECIMAL(10, 0)    NOT NULL,
    FECHA           DATE              NOT NULL,
    PRIMARY KEY (COTIZACIONID)
)ENGINE=MYISAM
;



-- 
-- TABLE: LINEA 
--

CREATE TABLE LINEA(
    MARCAID    DECIMAL(10, 0)    NOT NULL,
    LINEAID    DECIMAL(10, 0)    NOT NULL,
    LINEA      VARCHAR(100)      NOT NULL,
    PRIMARY KEY (MARCAID, LINEAID)
)ENGINE=MYISAM
;



-- 
-- TABLE: MARCA 
--

CREATE TABLE MARCA(
    MARCAID    DECIMAL(10, 0)    NOT NULL,
    MARCA      VARCHAR(100)      NOT NULL,
    PRIMARY KEY (MARCAID)
)ENGINE=MYISAM
;



-- 
-- TABLE: TIPO 
--

CREATE TABLE TIPO(
    TIPOID    DECIMAL(10, 0)    NOT NULL,
    TIPO      VARCHAR(100)      NOT NULL,
    PRIMARY KEY (TIPOID)
)ENGINE=MYISAM
;



-- 
-- TABLE: VEHICULO 
--

CREATE TABLE VEHICULO(
    VEHICULOID    DECIMAL(10, 0)    NOT NULL,
    TIPOID        DECIMAL(10, 0)    NOT NULL,
    MARCAID       DECIMAL(10, 0)    NOT NULL,
    LINEAID       DECIMAL(10, 0)    NOT NULL,
    CC            DECIMAL(10, 0)    NOT NULL,
    COLOR         VARCHAR(64)       NOT NULL,
    MODELO        VARCHAR(4)        NOT NULL,
    PRECIO        DECIMAL(10, 2)    NOT NULL,
    PRIMARY KEY (VEHICULOID)
)ENGINE=MYISAM
;



-- 
-- TABLE: AGENTE 
--

ALTER TABLE AGENTE ADD CONSTRAINT RefCONCESIONARIO4 
    FOREIGN KEY (CONCESIONARIOID)
    REFERENCES CONCESIONARIO(CONCESIONARIOID)
;


-- 
-- TABLE: COTIZACION 
--

ALTER TABLE COTIZACION ADD CONSTRAINT RefCLIENTE5 
    FOREIGN KEY (CLIENTEID)
    REFERENCES CLIENTE(CLIENTEID)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefAGENTE6 
    FOREIGN KEY (AGENTEID)
    REFERENCES AGENTE(AGENTEID)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefVEHICULO7 
    FOREIGN KEY (VEHICULOID)
    REFERENCES VEHICULO(VEHICULOID)
;


-- 
-- TABLE: LINEA 
--

ALTER TABLE LINEA ADD CONSTRAINT RefMARCA12 
    FOREIGN KEY (MARCAID)
    REFERENCES MARCA(MARCAID)
;


-- 
-- TABLE: VEHICULO 
--

ALTER TABLE VEHICULO ADD CONSTRAINT RefLINEA3 
    FOREIGN KEY (MARCAID, LINEAID)
    REFERENCES LINEA(MARCAID, LINEAID)
;

ALTER TABLE VEHICULO ADD CONSTRAINT RefTIPO10 
    FOREIGN KEY (TIPOID)
    REFERENCES TIPO(TIPOID)
;


